In [1]:
import numpy as np
from scipy.linalg import svd

ratings_data = np.array([
    [5, 4, 0, 2, 1],
    [3, 2, 0, 4, 5],
    [0, 0, 5, 4, 3],
    [1, 2, 3, 0, 0]
])

U, sigma, VT = svd(ratings_data)

num_factors_to_keep = 2
important_factors = VT[:num_factors_to_keep]

print("Important factors affecting ratings:")
for i, factor in enumerate(important_factors):
    print(f"Factor {i+1}: {factor}")

reconstructed_ratings = np.dot(np.dot(U[:, :num_factors_to_keep], np.diag(sigma[:num_factors_to_keep])), VT[:num_factors_to_keep])

print("\nReconstructed ratings matrix:")
print(reconstructed_ratings)

Important factors affecting ratings:
Factor 1: [0.45922727 0.36518135 0.30109198 0.54859021 0.51395068]
Factor 2: [-0.55158596 -0.41231307  0.67355667  0.21091554  0.16609308]

Reconstructed ratings matrix:
[[ 4.57177777  3.53502083 -0.95622707  2.1392875   2.12453123]
 [ 3.60005087  2.84160196  1.52676599  3.60015792  3.39820309]
 [-0.19069896 -0.02771994  4.75049211  3.86888449  3.47621394]
 [ 0.60562717  0.49855717  1.06422405  1.28405193  1.18266984]]
